#!/usr/bin/env bash

floaterm_win=$(hyprctl clients | grep "floaterm")
notify-send $floaterm_win

if [ -z $floaterm_win ]
then
  notify-send $floaterm_win
  env foot --title floaterm
else
  hyprctl dispatch togglespecialworkspace floaterm
fi
